name: test

on:
  push:
    branches:
      - main

jobs:
  googletest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: up
        shell: bash
        run: make d-up

      - name: build
        shell: bash
        run: make d-build

      - name: test
        shell: bash
        run: make d-test
